### ISSUE TITLE
Rebuild Bounty?

### ISSUE THREAD

**Issue by mmatongo** [nanocafe/website#1]
Hey, I saw your bounty on reddit and was interested in working on the project.
I'm a huge fan of react but it tends to be slow especially for apps with lots of front end activity.

Is there a bounty for rebuilding using another framework to improve on this?

**Comment by saizo-nanocafe** [comment]
Hi Daniel,

Thank you for the email!

At the moment we don't have any plans on changing the server architecture away from react unless I'm misunderstanding and you mean just for the news feed; the current news feed is outdated and definitely needs to get updated both code/visually, what did you have in mind? If you wanted to tackle #1, you can use another framework to improve on the current news feed we have and the same bounty would apply.

Best,
Saiad M.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐
